### PR TITLE
Safer versionService for null values + closed streams

### PR DESCRIPTION
**Pull request by sfrancini-fcg**
Hi,
I made some fixes to MockVersionService to improve its null safety. I also closed both the inputstreams with a try-with-resource.

### CODE REVIEW

**Comment by flashboss** [comment]
Thanks for the contribution but let me understand, are there cases in which the name, type and content properties can be null?

**Comment by sfrancini-fcg** [comment]
Hi,
yes, I am using your library in conjunction with another one that at the time of creating the version only sets “versionType” and “description”, so all other properties were null to me.
As for streams, instead, good to know, I will fix it as soon as possible!

**Comment by flashboss** [comment]
PROP_NAME too?

**Comment by sfrancini-fcg** [comment]
Yes, PROP_NAME is null as well. I was wondering if it would be better to get name property from the nodeRef (instead of setting it with System.currentTimeMillis() as I did) in case of versionProperties without the PROP_NAME property set.

**Comment by flashboss** [comment]
I find it rather strange that the PROP_NAME can be null. Can you send me the unit test you are doing?

**Comment by sfrancini-fcg** [comment]
Hi,
sorry for the late reply.
To create a new version, I'm using a custom library that does the following:

```
    public Version createNewVersion(NodeRef nodeRef, String versionComment, VersionType versionType) {
        Preconditions.checkArgument(StoreRef.STORE_REF_WORKSPACE_SPACESSTORE.equals(nodeRef.getStoreRef()), "I can't create a new version of node out of " + StoreRef.STORE_REF_WORKSPACE_SPACESSTORE);
        Map<String, Serializable> versionProperties = Maps.newHashMap();
        versionProperties.put("versionType", versionType);
        versionProperties.put("description", versionComment);
        return this.versionService.createVersion(nodeRef, versionProperties);
    }
```

As you can see, the `createVersion` method of VersionService is called with only the nodeRef and the version properties containing only versionType and description, so there is no PROP_NAME in it.
I cannot change this implementation since it's used in a wide variety of projects and works correctly.

Please let me know if you need more information!

**Comment by flashboss** [comment]
Ok, I released the 7.3.0.20 version. You can try. Let me know if it is all ok

**Pull request closed without merging**
